id: a351176dc61d4941b66b50a6043ec736
initial_creation_type: ocr
source_metadata:
  volumes:
    2eee1e34deea4286b61db95c7ca0a68c:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: ''
      total_pages: 1182
      volume_number: 111
